### ISSUE TITLE
Error with test unit: cannot import name `KW_ONLY` from `dataclasses`

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#134]
I tried to add some test data and the test unit failed: 

```python
Run xvfb-run pytest -vvv .
  xvfb-run pytest -vvv .
  shell: /usr/bin/bash -l {0}
  env:
    DISPLAY: :99.0
    MAMBA_ROOT_PREFIX: /home/runner/micromamba
    MAMBA_EXE: /home/runner/micromamba-bin/micromamba
    CONDARC: /home/runner/work/_temp/setup-micromamba/.condarc
============================= test session starts ==============================
platform linux -- Python 3.9.19, pytest-8.[2](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:2).1, pluggy-1.5.0 -- /home/runner/micromamba/envs/anaconda-test-env-py-[3](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:3).9/bin/python3.9
cachedir: .pytest_cache
PyQt5 5.15.9 -- Qt runtime 5.15.8 -- Qt compiled 5.15.8
rootdir: /home/runner/work/mdaviz/mdaviz
configfile: pyproject.toml
plugins: cov-5.0.0, qt-[4](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:4).4.0, xvfb-3.0.0, anyio-4.3.0
collecting ... collected 2 items

mdaviz/tests/test_aboutdialog.py::test_about_starts PASSED               [ [5](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:5)0%]
mdaviz/tests/test_app.py::test_app_startup FAILED                        [100%]

=================================== FAILURES ===================================
_______________________________ test_app_startup _______________________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mainwindow.py", line 270, in setSubFolderPath
    self.mvc_folder = MDA_MVC(self)
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line 101, in __init__
    self.setup()
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line 107, in setup
    from .mda_file import MDAFile
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file.py", line 34, in <module>
    from .mda_file_table_view import MDAFileTableView
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_view.py", line 1[6](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:6), in <module>
    from .mda_file_table_model import ColumnDataType
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_model.py", line 34, in <module>
    from dataclasses import KW_ONLY
ImportError: cannot import name 'KW_ONLY' from 'dataclasses' (/home/runner/micromamba/envs/anaconda-test-env-py-3.9/lib/python3.9/dataclasses.py)
________________________________________________________________________________
----------------------------- Captured stdout call -----------------------------
Settings are saved in: /home/runner/.config/BCDA-APS/mdaviz.ini
----------------------------- Captured stderr call -----------------------------
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mainwindow.py", line 2[7](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:7)0, in setSubFolderPath
    self.mvc_folder = MDA_MVC(self)
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line 101, in __init__
    self.setup()
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line 107, in setup
    from .mda_file import MDAFile
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file.py", line 34, in <module>
    from .mda_file_table_view import MDAFileTableView
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_view.py", line 16, in <module>
    from .mda_file_table_model import ColumnDataType
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_model.py", line 34, in <module>
    from dataclasses import KW_ONLY
ImportError: cannot import name 'KW_ONLY' from 'dataclasses' (/home/runner/micromamba/envs/anaconda-test-env-py-3.[9](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:10)/lib/python3.9/dataclasses.py)
________________________________________________________________________________
=============================== warnings summary ===============================
../../../micromamba/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/setuptools_scm/git.py:167
  /home/runner/micromamba/envs/anaconda-test-env-py-3.9/lib/python3.9/site-packages/setuptools_scm/git.py:167: UserWarning: "/home/runner/work/mdaviz/mdaviz" is shallow and may cause errors
    warnings.warn(f'"{wd.path}" is shallow and may cause errors')

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED mdaviz/tests/test_app.py::test_app_startup - Failed: CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mainwindow.py", line 270, in setSubFolderPath
    self.mvc_folder = MDA_MVC(self)
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line [10](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:11)1, in __init__
    self.setup()
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_folder.py", line 107, in setup
    from .mda_file import MDAFile
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file.py", line 34, in <module>
    from .mda_file_table_view import MDAFileTableView
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_view.py", line [16](https://github.com/BCDA-APS/mdaviz/actions/runs/9340518196/job/25706174812#step:8:17), in <module>
    from .mda_file_table_model import ColumnDataType
  File "/home/runner/work/mdaviz/mdaviz/mdaviz/mda_file_table_model.py", line 34, in <module>
    from dataclasses import KW_ONLY
ImportError: cannot import name 'KW_ONLY' from 'dataclasses' (/home/runner/micromamba/envs/anaconda-test-env-py-3.9/lib/python3.9/dataclasses.py)
________________________________________________________________________________
==================== 1 failed, 1 passed, 1 warning in 1.01s ====================
Error: Process completed with exit code 1.
```

**Comment by rodolakis** [comment]
For now I have remove the mda files from the `tests/test_data` folder

**Comment by rodolakis** [comment]
This test passes in v1.1.0
