### ISSUE TITLE
pb with logging model - impossible to start app after pip install mdaviz

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#165]
Tested on a old conda env at 29; we got the same problem yesterday with Hao MacBook. 

```bash
(base) [clueless ~/bin/mdaviz] conda activate bluesky_2022_2
(bluesky_2022_2) [clueless ~/bin/mdaviz] pip install mdaviz
Collecting mdaviz
  Downloading mdaviz-1.0.0-py3-none-any.whl (1.7 MB)
     |████████████████████████████████| 1.7 MB 1.9 MB/s 
Requirement already satisfied: PyYAML in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from mdaviz) (6.0)
Collecting tiled
  Downloading tiled-0.1.0b4-py3-none-any.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 22.3 MB/s 
Requirement already satisfied: matplotlib in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from mdaviz) (3.5.1)
Requirement already satisfied: PyQt5 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from mdaviz) (5.15.7)
Requirement already satisfied: python-dateutil>=2.7 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (2.8.2)
Requirement already satisfied: packaging>=20.0 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (21.3)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (1.4.2)
Requirement already satisfied: cycler>=0.10 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (0.11.0)
Requirement already satisfied: numpy>=1.17 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (1.22.3)
Requirement already satisfied: pillow>=6.2.0 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (9.0.1)
Requirement already satisfied: pyparsing>=2.2.1 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from matplotlib->mdaviz) (4.25.0)
Requirement already satisfied: six>=1.5 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from python-dateutil>=2.7->matplotlib->mdaviz) (1.16.0)
Requirement already satisfied: PyQt5-Qt5>=5.15.0 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from PyQt5->mdaviz) (5.15.2)
Requirement already satisfied: PyQt5-sip<13,>=12.11 in /home/beams22/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages (from PyQt5->mdaviz) (12.11.0)
Installing collected packages: tiled, mdaviz
Successfully installed mdaviz-1.0.0 tiled-0.1.0b4
(bluesky_2022_2) [clueless ~/bin/mdaviz] cd
(bluesky_2022_2) [clueless ~] mdaviz
Traceback (most recent call last):
  File "/home/beams/29IDUSER/.conda/envs/bluesky_2022_2/bin/mdaviz", line 8, in <module>
    sys.exit(main())
  File "/home/beams/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages/mdaviz/app.py", line 62, in main
    options = command_line_interface()
  File "/home/beams/29IDUSER/.conda/envs/bluesky_2022_2/lib/python3.9/site-packages/mdaviz/app.py", line 44, in command_line_interface
    choices=[k.lower() for k in logging.getLevelNamesMapping()],
AttributeError: module 'logging' has no attribute 'getLevelNamesMapping'
(bluesky_2022_2) [clueless ~] 
```

**Comment by rodolakis** [comment]
@prjemian. unless you want to quickly look at it,  I am tempted to just turn off command line option for a quick 1.0.1 patch so we can use it, since I don't have the time to troubleshoot.

**Comment by prjemian** [comment]
Can you install mdaviz into its own conda environment instead?  That would isolate its other package requirements, to eliminate conflicts.
