### ISSUE TITLE
app crashes when trying to open folder with wrong permissions: drwx------

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#51]
```bash
Traceback (most recent call last):
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mainwindow.py", line 177, in setFolderPath
    self.setSubfolderList(get_all_subfolders(folder_path, folder_path.name))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mainwindow.py", line 174, in get_all_subfolders
    subfolder_list += get_all_subfolders(item, new_parent_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mainwindow.py", line 174, in get_all_subfolders
    subfolder_list += get_all_subfolders(item, new_parent_path)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams22/29IDUSER/bin/mdaviz/mdaviz/mainwindow.py", line 165, in get_all_subfolders
    for item in folder_path.iterdir():
  File "/home/beams/29IDUSER/.conda/envs/mdaviz/lib/python3.11/pathlib.py", line 931, in iterdir
    for name in os.listdir(self):
                ^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/net/s29data/export/old_data_29idd/lost+found'
^C
[1]+  Aborted                 (core dumped) mdaviz
```

**Comment by rodolakis** [comment]
```bash
[clueless ~] ll /net/s29data/
total 4
drwxr-xr-x 10 root root 4096 Sep 13  2022 export
```
