### ISSUE TITLE
App crashed trying to open HOME folder on my beams account

### ISSUE THREAD

**Issue by apsIEX** [BCDA-APS/mdaviz#86]
```python
====== Selected file: mda_0001.mda
Mode is set to Auto-off

Responder: action='clear'

doPlot called: args=('clear', {'Y': [2], 'X': 1})

Responder: action='add'

doPlot called: args=('add', {'Y': []})
Traceback (most recent call last):
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder.py", line 279, in doPlot
    datasets, plot_options = to_datasets(
                             ^^^^^^^^^^^^
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/select_fields_table_view.py", line 201, in to_datasets
    "y_units": y_units,
               ^^^^^^^
UnboundLocalError: cannot access local variable 'y_units' where it is not associated with a value
Aborted (core dumped)
```

Can't reproduce this one any more, must be fixed in the current state of the code.

**Comment by apsIEX** [comment]
Another one (trying to open HOME folder on my beams account):

Traceback (most recent call last):
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder_table_model.py", line 58, in data
    return action(file)
           ^^^^^^^^^^^^
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder_table_model.py", line 22, in <lambda>
    "Points": lambda file: self.get_file_pts(file),
                           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/beams3/RODOLAKIS/src/mdaviz/mdaviz/mda_folder_table_model.py", line 89, in get_file_pts
    return readMDA(str(filepath))[1].curr_pt
           ~~~~~~~~~~~~~~~~~~~~~~^^^
TypeError: 'NoneType' object is not subscriptable
Aborted (core dumped)

**Comment by rodolakis** [comment]
related to #124
