### ISSUE TITLE
Keep relevant folder/file tabs open

### ISSUE THREAD

**Issue by rodolakis** [BCDA-APS/mdaviz#90]
Now when a new file and/or folder is selected, I would like to KEEP the table views tabs (in both `MDAFolderTableView` and `SelectFieldsTableView`) as long as some content from this file/folder is displayed on the graph.

![Image](https://github.com/BCDA-APS/mdaviz/assets/39918069/76f7f96a-0f29-43f0-995d-68ecb1978bad)

For example in this picture, if I select mda_0024.mda, as long as there are some data from mda_0023 displayed on the plot, I would like to keep the tab for mda_0023.mda in my field table view, but add a new one for mda_0024 (and bring it in focus/front). 

This will allow some manipulation on the file/folder (eg change normalization by I0, add a detector, etc.) without having to reopen/look for the previous folder/file.

**Comment by rodolakis** [comment]
BTW, not a big deal, but when there is no content (like below), the tab in the field table view widget still shows the file name of the last file displayed. 

![Image](https://github.com/BCDA-APS/mdaviz/assets/39918069/cb03e652-1e5d-4d51-9427-cc5fc21f1848)

**Comment by rodolakis** [comment]
This issue will help with the following event crash that occurs in auto-add mode:
- plot curve 1
- add curve 2
- remove curve 1 - it uncheck the box from the corresponding detector which ends up with 1 positioner selected only
- add curve 3: crash => trying to match the pv but there was no detector selected so `KeyError`



```python
========= Selected file: mda_0008.mda in /Users/fannysimoes/src/mdaviz/mdaviz/data/test_folder1

doPlot called: args=('add', {'X': 1, 'Y': [2]})


========= Selected file: mda_0007.mda in /Users/fannysimoes/src/mdaviz/mdaviz/data/test_folder1
Traceback (most recent call last):
  File "/Users/fannysimoes/src/mdaviz/mdaviz/mda_folder.py", line 308, in doFileSelected
    self.updateSelectionForNewPVs(oldPvList, newPvList, verbose)
  File "/Users/fannysimoes/src/mdaviz/mdaviz/mda_folder.py", line 205, in updateSelectionForNewPVs
    changes_made |= self.updateDetectorSelection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fannysimoes/src/mdaviz/mdaviz/mda_folder.py", line 227, in updateDetectorSelection
    for old_idx in self.selectionField()["Y"]:
                   ~~~~~~~~~~~~~~~~~~~~~^^^^^
KeyError: 'Y'
Abort trap: 6
```

**Comment by rodolakis** [comment]
Tabs can be close easily with 
```xml
         <property name="tabsClosable">
          <bool>true</bool>
         </property>
```



![Image](https://github.com/BCDA-APS/mdaviz/assets/39918069/4484c87f-7584-47ba-a161-70cad08b2487)

**Comment by rodolakis** [comment]
Related to this https://github.com/BCDA-APS/mdaviz/issues/39#issuecomment-1724230879
Related to https://github.com/BCDA-APS/mdaviz/issues/41

**Comment by rodolakis** [comment]
- need to dissociate `self.select_fields_tableview`, which is an instance from `SelectFieldsTableView`, vs the `tabWidget` that contains the actual table view /model:
    - when creating an instance of `SelectFieldsTableView` in `MDA_MVC`, it created the entire panels and load the UI file that contains the layout with the `tabWidget` but also the `mode` pull down menu and the `clear` button, etc.
    -

**Comment by rodolakis** [comment]
Going home, getting closer but still some work to do:


![Image](https://github.com/BCDA-APS/mdaviz/assets/39918069/a22ca793-646f-45a1-8a28-c7dbbf60e9fb)

**Comment by rodolakis** [comment]
Make sure to disable open the same file in multiple tabs (it is the case now)
